{
    'name': 'Qataria Retail Modifications',
    'version': '16.0.0.0',
    'summary': 'Qataria Retail Business module',
    'description': """Custom additions to meet specs of Qataria retail""",
    'website': 'https://www.gate-its.com',
    'author': "Gate ITS",
    'images': [
        'static/description/icon.png',
    ],
    'category': 'Accounting',
    'depends': [
        'account',
        'hr',
        'sale',
        'stock',
        'purchase',
        'product',
        'base',
        'accounting_pdf_reports',
    ],
    'data': [
        'views/sales.xml',
        'views/account.xml',
        'views/purchases.xml',
        'views/account_payment.xml',
        'views/stock.xml',
        'report/reports.xml',
        'report/official_report.xml',
        'report/partner_aged_report.xml',
        'wizard/partner_aged.xml',

    ],
    'qweb': [],
    'installable': True,
    'application': True,
    'license': 'GPL-3',
    'auto_install': False,
}
