{
    'name': 'Qataria Retail Modifications',
    'version': '16.0.0.0',
    'summary': 'Qataria Retail Business module',
    'author': "Amany Elhwary",
    'description': """Custom additions to meet specs of Qataria retail""",
    'Facebook Profile': 'https://www.facebook.com/profile.php?id=100011030985587',
    'images': [
        'static/description/icon.png',
    ],
    'category': 'Accounting',
    'depends': [
        'account',
        'hr',
        'sale',
        'stock',
        'purchase',
        'product',
        'base',
    ],
    'data': [
        'views/sales.xml',
        'views/account.xml',
        'views/purchases.xml',
        'views/account_payment.xml',
        'views/stock.xml',
        'report/reports.xml',
        'report/official_report.xml',
    ],
    'qweb': [],
    'installable': True,
    'application': True,
    'license': 'GPL-3',
    'auto_install': False,
}
